stages:
  - test
test:
  script:
    - powershell -command "copy .env.testing .env"
    - powershell -command "composer install"
    - powershell -command "composer dumpautoload"
    - powershell -command "php artisan migrate"
    - vendor\bin\phpunit
  allow_failure: true

