image: php:7.4-fpm

stages:
  - test
 
unit_test:
  stage: test
  before_script:
    - apt update
    - apt install -qq git libpng-dev libonig-dev libxml2-dev zip unzip -y
    - apt-get clean && rm -rf /var/lib/apt/lists/*
    - docker-php-ext-configure zip --with-libzip
    - docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip
    - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  
  script:
    - cp .env.testing .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit