  # Install Node dependencies.
  - npm install

  # Copy over testing configuration.
  - cp .env.testing .env
  # Run npm build
  - npm run dev

  # Generate an application key. Re-cache.
  - php artisan key:generate
  - php artisan config:cache

  # Run database migrations.
  - php artisan migrate
  
  # Run database seed
  #- php artisan db:seed

test:
  script:
    # run laravel tests
    - php vendor/bin/phpunit --coverage-text --colors=never
    # run frontend tests
    # if you have any task for testing frontend
    # set it in your package.json script
    # comment this out if you don't have a frontend test
    - npm test
