image: php:7.4-cli

stages:
  - test

unit_test:
  stage: test
  before_script:
    - apt update
    - apt install -qq git libpng-dev libonig-dev libxml2-dev libzip-dev zip unzip -y

    - apt-get clean && rm -rf /var/lib/apt/lists/*

    - docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip
    - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - rm -rf vendor/
  script:
    - cp .env.testing .env
    - composer install
    - php artisan migrate
    - vendor/bin/phpunit
    - php artisan dusk
