image: php:7.4-cli

stages:
  - test
 
unit_test:
  stage: test
  before_script:
    - apt install composer
  script:
    - cp .env.testing .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit