image: php:7.4-cli

stages:
  - test
 
unit_test:
  stage: test
  before_script:
    - docker-php-ext-install openssl pdo_mysql zip
    - apt update
    - apt install -qq git curl libmcrypt-dev libjpeg-dev libpng-dev libfreetype6-dev libbz2-dev -y
    - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - cp .env.testing .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit